// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDeZHAj0TP25gF4pYLZoY5xeR_svTbEw8',
    appId: '1:838642173236:web:f6d236bdfea5c76e60d161',
    messagingSenderId: '838642173236',
    projectId: 'cht---chronical-health-tracker',
    authDomain: 'cht---chronical-health-tracker.firebaseapp.com',
    storageBucket: 'cht---chronical-health-tracker.appspot.com',
    measurementId: 'G-YE69TDFTC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7b63ydqQwyUS12tClvJyUofX0CpKwjHY',
    appId: '1:838642173236:android:c1737aeec0d49fdd60d161',
    messagingSenderId: '838642173236',
    projectId: 'cht---chronical-health-tracker',
    storageBucket: 'cht---chronical-health-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiRVrVrUAEgQtCro-UxfS3_MKNzFUvh_U',
    appId: '1:838642173236:ios:8cb9a436a8ccf09860d161',
    messagingSenderId: '838642173236',
    projectId: 'cht---chronical-health-tracker',
    storageBucket: 'cht---chronical-health-tracker.appspot.com',
    iosClientId: '838642173236-1jd5a44sihik7u7qqh4un594dhclq9p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cht2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiRVrVrUAEgQtCro-UxfS3_MKNzFUvh_U',
    appId: '1:838642173236:ios:de48e6c02092e82d60d161',
    messagingSenderId: '838642173236',
    projectId: 'cht---chronical-health-tracker',
    storageBucket: 'cht---chronical-health-tracker.appspot.com',
    iosClientId: '838642173236-eflbc467k1lqpjlmd24ascj48i15pmnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cht2.RunnerTests',
  );
}
